title: Scaldi
description: "Scaldi - Lightweight Dependency Injection Library"
baseurl: "/scaldi-website"
url: "http://scaldi.org"
theme: flatly

version:
  scaldi: 0.3.2
  scaldi-play: 0.3.3
  scaldi-akka: 0.3.3

markdown: kramdown
permalink: pretty

gems:
- jekyll-mentions
- jekyll-redirect-from
- jekyll-sitemap
